# Generated by Django 2.2.2 on 2019-06-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.CharField(choices=[('ac', 'activo'), ('in', 'inactivo')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('municipios', models.ManyToManyField(to='ubicaciones.Municipio')),
            ],
        ),
    ]
