# Generated by Django 2.2.2 on 2019-06-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterField(
            model_name='region',
            name='municipios',
            field=models.ManyToManyField(blank=True, to='ubicaciones.Municipio'),
        ),
    ]
